#!/bin/bash

name='what-your-droplet-is-called'

# Find a droplet id that matches our name
droplet_id=$(doctl compute droplet list $name* --format "ID" --no-header)

#Let's make sure the snapshot has a unique name
now=$(date +%s)
sName="$name-snapshot-$now"

# Change the webpage to show that we are offline
cp /home/jadinme/radio.jadin.me/offline.html /home/jadinme/radio.jadin.me/index.html

# shutdown droplet and take a snapshot
doctl compute droplet-action shutdown $droplet_id --wait
doctl compute droplet-action snapshot $droplet_id --snapshot-name $sName --wait

# Delete the droplet
doctl compute droplet delete $droplet_id -f
