#!/bin/bash

name='what-your-droplet-is-called'
image_id_path='/path/to/image_id'

# Find a droplet id that matches our name
droplet_id=$(doctl compute droplet list $name* --format "ID" --no-header)

#Let's make sure the snapshot has a unique name
now=$(date +%Y%m%d_%H%M%S)
sName="$name-snapshot-$now"

# Change the webpage to show that we are offline
echo "Copying offline.html over the top of index.html"
cp /home/jadinme/radio.jadin.me/offline.html /home/jadinme/radio.jadin.me/index.html

# shutdown droplet and take a snapshot
echo ""
echo "Shutting down droplet $droplet_id"
doctl compute droplet-action shutdown $droplet_id --wait
echo ""
echo "Taking snapshot of droplet $droplet_id"
doctl compute droplet-action snapshot $droplet_id --snapshot-name $sName --wait

# write id of the most recent image to disk so we can call it later
image_id=$(doctl compute image list --format "ID" | tail -n 1)
echo $image_id > $image_id_path

# Delete the droplet
echo ""
echo "Deleting droplet $droplet_id"
doctl compute droplet delete $droplet_id -f